FROM mcr.microsoft.com/dotnet/core/sdk:3.1

RUN mkdir -p /usr/src
WORKDIR /usr/src/

COPY Lusid.Drive.Sdk.sln /usr/src/
COPY Lusid.Drive.Sdk/ /usr/src/Lusid.Drive.Sdk/
COPY Lusid.Drive.Sdk.Tests/ /usr/src/Lusid.Drive.Sdk.Tests/
