version: "3"

services:

  drive-sdk-csharp-preview-build:
    build: .
    container_name: drive-sdk-csharp-preview-build
    image: finbourne/drive-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_DRIVE_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src