version: "3"

services:

  lusid-sdk-csharp-test:
    build: .
    container_name: drive-sdk-csharp-test
    image: finbourne/drive-sdk-csharp-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_DRIVE_API_URL=${FBN_BASE_API_URL}/drive
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src
    command: 
      - /bin/bash
      - -ce
      - |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test -v n Lusid.Drive.Sdk.Tests